#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 raito kaneko 2434.raito@gmial.com
# SPDX-License-Identifier: BSD-3-Clause
import sys
   
ans = 0.0
for line in sys.stdin:
    ans += float(line)
     
print(ans)
